export const PERMISSIONS_BY_ROLE = {
  road_authority: [
    'traffic:read',
    'traffic:update',
    'parking:read',
    'parking:book',
    'parking:release:any',
    'fine:read',
    'fine:issue',
    'fine:cancel',
    'fine:pay:any',
    'challan:create',
    'challan:read',
    'challan:update',
    'challan:cancel',
    'violation:document',
    'violation:photographs',
    'road-issues:read',
    'road-issues:write',
    'report:generate'
  ],
  municipal_corp: [
    'traffic:read',
    'traffic:update',
    'traffic:manual-control',
    'parking:read',
    'parking:book',
    'parking:release:any',
    'parking:send-alert',
    'parking:amenities:manage',
    'traffic:signals:view',
    'traffic:signals:optimize',
    'traffic:monitoring:real-time',
    'encroachment:monitor',
    'encroachment:report',
    'emergency:read',
    'road-issues:read',
    'road-issues:write',
    'report:generate',
    'admin:reports'
  ],
  traffic_police: [
    'traffic:read',
    'traffic:update',
    'traffic:manual-control',
    'parking:read',
    'fine:read',
    'fine:issue',
    'fine:cancel',
    'emergency:activate',
    'emergency:read',
    'emergency:complete',
    'violation:document',
    'violation:photographs',
    'challan:create',
    'challan:read',
    'challan:issue',
    'audit:read'
  ],
  admin: [
    'traffic:read',
    'traffic:update',
    'traffic:manual-control',
    'parking:read',
    'parking:book',
    'parking:release:any',
    'parking:send-alert',
    'fine:read',
    'fine:issue',
    'fine:cancel',
    'fine:pay:any',
    'emergency:read',
    'emergency:activate',
    'emergency:complete',
    'payment:create:any',
    'payment:view:any',
    'audit:read',
    'admin:read',
    'road-issues:read',
    'road-issues:write'
  ],
  agent: [
    'traffic:read',
    'traffic:update',
    'traffic:signals:optimize',
    'traffic:monitoring:real-time',
    'traffic:predictive-analytics',
    'emergency:read',
    'emergency:coordinate',
    'parking:optimize',
    'crowd:density:analyze',
    'logistics:coordinate'
  ],
  citizen: [
    'traffic:read',
    'road-issues:read',
    'parking:read',
    'parking:book',
    'parking:release:own',
    'fine:read:own',
    'fine:pay:own',
    'emergency:read',
    'payment:create:own',
    'payment:view:own'
  ],
  drivelegal: [
    'traffic:read',
    'road-issues:read',
    'parking:read',
    'fine:read:own'
  ]
};

export function getPermissionsForRole(role) {
  return PERMISSIONS_BY_ROLE[role] || [];
}
